language: generic
sudo: required

matrix:
  include:
    - os: linux
      services: docker
      env: CONTAINER=centos:6
    - os: linux
      services: docker
      env: CONTAINER=centos:7

before_install:
  - sudo apt-get -qq update && sudo apt-get install -y bash

before_script:
  - export TMPDIR=$TRAVIS_BUILD_DIR/tmp && mkdir -p $TMPDIR

script:
  - sudo bash ./build/build_docker.sh
